### ISSUE TITLE
Problems with installing Radiant

### ISSUE THREAD

**Issue by tiaho** [jnmaloof/debian-lab-server#1]
Once again, I'm stuck. Sigh. I'm getting this error when I try to create a new Radiant project.

tiffany@debianbox:~/RadiantTest$ bundle exec rake db:bootstrap
Your Gemfile lists the gem compass-rails (~> 1.0.3) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
/usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:212:in `initialize': Permission denied @ rb_sysopen - /usr/lib/ruby/gems/1.9.1/extensions/x86-linux/2.1.0-static/RedCloth-4.2.9/gem_make.out (Errno::EACCES)
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:212:in `open'
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:212:in `write_gem_make_out'
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:132:in `build_error'
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:171:in `rescue in build_extension'
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:156:in `build_extension'
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
	from /usr/local/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
	from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
	from /usr/local/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
	from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
	from /usr/local/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
	from /usr/local/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
	from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
	from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
	from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
	from /usr/local/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
	from /usr/local/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /usr/local/lib/ruby/2.1.0/securerandom.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/resolv.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/remote_fetcher.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/spec_fetcher.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/source/rubygems.rb:3:in `<top (required)>'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/source_list.rb:9:in `initialize'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/dsl.rb:20:in `new'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/dsl.rb:20:in `initialize'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/dsl.rb:9:in `new'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/dsl.rb:9:in `evaluate'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/definition.rb:25:in `build'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler.rb:154:in `definition'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler.rb:117:in `setup'
	from /usr/lib/ruby/gems/1.9.1/gems/bundler-1.7.4/lib/bundler/setup.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by mfcovington** [comment]
Using DjangoCMS instead.
